### ISSUE TITLE
it's called P-NP lmao

### ISSUE THREAD

**Issue by afkvido** [Prodigy-Hacking-2/PN-P#1]
<img width="1367" alt="git gud" src="https://user-images.githubusercontent.com/69060894/162393709-a6003e72-1e01-4b90-8f1c-b9ea6ad0b333.png">

###### however, it's still called P-NP

**Comment by donaldli2020** [comment]
###### The issue?

**Comment by afkvido** [comment]
###### it looks like a ripoff of P-NP

**Comment by donaldli2020** [comment]
.

**Comment by donaldli2020** [comment]
###### Btw, did I zoom out like 67%?

**Comment by afkvido** [comment]
###### IDRK

**Comment by afkvido** [comment]
<h6><img width="591" alt="Screen Shot 2022-04-11 at 6 05 24 PM" src="https://user-images.githubusercontent.com/69060894/162692307-62ed4fb5-6cbf-4b45-bb99-a0d668c31a9c.png"></h6>

<h6>you not gettin any money lmao</h6>

**Comment by donaldli2020** [comment]
i could just edit it...

**Comment by donaldli2020** [comment]
![image](https://user-images.githubusercontent.com/74021676/163884032-7244744a-bc64-4c7b-8537-ef351999cee7.png)

**Comment by donaldli2020** [comment]
PN-P

**Comment by donaldli2020** [comment]
lmao
